// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartDomainDrivenDesign.OrderSample.Infrastructure.Data;

namespace SmartDomainDrivenDesign.OrderSample.Infrastructure.Data.OrdersDbContextMigrations
{
    [DbContext(typeof(OrdersDbContext))]
    partial class OrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("SmartDomainDrivenDesign.OrderSample.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("SmartDomainDrivenDesign.OrderSample.Domain.Orders.OrderLine", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Item")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderLine");
                });

            modelBuilder.Entity("SmartDomainDrivenDesign.OrderSample.Domain.Orders.OrderLine", b =>
                {
                    b.HasOne("SmartDomainDrivenDesign.OrderSample.Domain.Orders.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId");

                    b.OwnsOne("SmartDomainDrivenDesign.OrderSample.Domain.Shared.Price", "UnitPrice", b1 =>
                        {
                            b1.Property<long>("OrderLineId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("OrderLineId");

                            b1.ToTable("OrderLine");

                            b1.WithOwner()
                                .HasForeignKey("OrderLineId");
                        });

                    b.OwnsOne("SmartDomainDrivenDesign.OrderSample.Domain.Shared.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<long>("OrderLineId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("MeasureUnits")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrderLineId");

                            b1.ToTable("OrderLine");

                            b1.WithOwner()
                                .HasForeignKey("OrderLineId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
